version: "3.7"

services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:80"
            - "8001:443"
    db:
        image: postgres:12

        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "admin"
            POSTGRES_USER: "admin"
        volumes:
            - db-data:/var/lib/postgresql/data1/pgdata
            
volumes:
    db-data:
